### PR TITLE
better extensibility - specify password in arguments

### PR DESCRIPTION
**Pull request by gaoDean**
adds optional pass argument to `add` and `edit`

### CODE REVIEW

**Comment by biox** [comment]
thanks for the PR - can you explain what the use-case for this is? i am very unlikely to add any extra arguments to any of the commands, because it violates some assumptions & increases the complexity of pa quite a bit.

**Comment by gaoDean** [comment]
thanks for responding, I totally understand if you don’t want to merge this, but the use case is so other integrations can interface with it. Let’s say you want a gui interface for some kind of app, where the user inputs the username and pass, and pa stores it. It would be much easier to just

**Comment by gaoDean** [comment]
Whoops misclick, I’ll keep on going tho. It would be much easier to just pass the password as an argument, unless you have an easier way?

**Comment by biox** [comment]
> unless you have an easier way?

i do! i would suggest just using age directly instead of using pa - pa is just a light wrapper for age, and i don't see much use in depending on it directly - age has a cli tool, but also has native libraries you can use that are specifically designed for just the sort of thing a GUI might want.

in short, it'd be better for you to just skip pa and depend directly on age. it could even remain pa-compatible if you'd like, so long as the identity files & stored passwords are in the correct place :blush:

**Comment by gaoDean** [comment]
Alright cool, thanks for responding so quickly!

**Comment by arcxio** [comment]
@gaoDean fyi you can also do this
```shell
~$ pa add name <<EOF 2>/dev/null
npassword
password
EOF
Generate a password? [y/n]: 
Enter password: 
Enter password (again): 
Saved 'name' to the store.
~$ pa show name
password
```
which is a hack, but it works nonetheless

**Pull request closed without merging**
