### PR TITLE
automatic git commits (#14)

### PR DESCRIPTION
**Pull request by arcxio**
if git is installed:

- if repo doesn't exist in the store, initialize, configure and commit everything to it 
- commit changed files on every add/del/edit

if it's not installed, no changes

requires no input from user to work

### CODE REVIEW

**Comment by biox** [comment]
this is great, thx so much for doing this footwork - i'm willing to merge now, but wanted to raise the potential for this to be disabled? wondering if we should supply an env var to allow users to opt-out of git tracking, even if they have git installed.

also, what does this stuff do?

```
        git config diff.age.binary true
        git config diff.age.textconv "age --decrypt -i \"$identities_file\""
        printf '%s\n' '*.age diff=age' >.gitattributes
```

also: would you be interested in becoming a `pa` maintainer? your coding style & concerns seem to line up well with the project.

**Comment by arcxio** [comment]
> but wanted to raise the potential for this to be disabled

I've thought about it too, but couldn't settle on a good way to do this. I guess opt-out env makes the most sense, I've added PA_NOGIT for this

> what does this stuff do?

I've added comments to explain what's going on here, in short it allows git to generate diffs for human viewing instead of just spewing out binary output. I've basically yoinked [these four lines from pass](https://git.zx2c4.com/password-store/tree/src/password-store.sh#n659)

> would you be interested in becoming a `pa` maintainer?

sure, I'd be glad!

**Comment by biox** [comment]
lgtm, i'm going to run this for a few days on my machine & make sure i don't notice regressions before merging - ty again!

**Comment by biox** [comment]
also i've added u as a collaborator, u should have an email now!

**Review by mbauhardt — APPROVED** [review]
+1

**Comment by biox** [comment]
works perfectly for me - merging now!

**Pull request merged**
